// react_assignment_2/src/components/CreateUser.js
import React, { useState } from "react";
import ViewUserModal from "./ViewUserModal";

const CreateUser = ({handleSubmit}) => {
  const [showModal, setShowModal] = useState(false);
  const [nameInput, setNameInput] = useState("");
  const [emailInput, setEmailInput] = useState("");
  const [phoneInput, setPhoneInput] = useState("");
  const [categoryInput, setCategoryInput] = useState("");
  const [genderInput, setGenderInput] = useState("");
  const [technologyInput, setTechnologyInput] = useState([]);
  const [error, setError] = useState("");

  const technologyInputHandler = (e) => {
    if (e.target.checked) {
      setTechnologyInput((prevState) => [...prevState, e.target.value]);
    } else {
      setTechnologyInput((prevState) =>
        prevState.filter((item) => item !== e.target.value)
      );
    }
  };

  const submitHandler = (e) => {
    e.preventDefault();
    if (nameInput.trim() == 0) {
      setError("Enter name");
      return;
    }
    if (!emailInput.includes("@")) {
      setError("Enter valid email");
      return;
    }
    if (phoneInput.trim() == 0 || phoneInput.length != 10) {
      setError("Enter valid phone(10 digit) ");
      return;
    }
    if (categoryInput.trim() == 0) {
      setError("Select Category");
      return;
    }
    if (genderInput.trim() == 0) {
      setError("Select gender");
      return;
    }
    if (technologyInput.length == 0) {
      setError("Select atleast 1 technology");
      return;
    }

    setError("");
    setShowModal(true);
  };

  const toggleModal = () => {
    setShowModal((prev) => !prev);
  };

  return (
    <>
      {showModal && (
        <ViewUserModal
          userDetails={{
            name: nameInput,
            phone: phoneInput,
            email: emailInput,
            gender: genderInput,
            category: categoryInput,
            technology: technologyInput,
          }}
          handleCancel={toggleModal}
          handleSubmit={handleSubmit}
        />
      )}
      <form onSubmit={submitHandler}>
        <h1 className="text-center">Enter Details</h1>
        {error && <p className="error">{error}</p>}
        <div className="form-group mb-3">
          <label htmlFor="name">Name</label>
          <input
            type="text"
            className="form-control"
            id="name"
            placeholder="Enter name"
            minLength={2}
            maxLength={30}
            value={nameInput}
            onChange={(e) => setNameInput(e.target.value)}
          />
        </div>
        <div className="form-group mb-3">
          <label>Gender</label>
          <div className="form-check form-check-inline">
            <input
              className="form-check-input"
              type="radio"
              name="gender"
              id="male"
              value="male"
              onChange={(e) => setGenderInput(e.target.value)}
            />
            <label className="form-check-label" htmlFor="male">
              Male
            </label>
          </div>
          <div className="form-check form-check-inline">
            <input
              className="form-check-input"
              type="radio"
              name="gender"
              id="female"
              value="female"
              onChange={(e) => setGenderInput(e.target.value)}
            />
            <label className="form-check-label" htmlFor="female">
              Female
            </label>
          </div>
        </div>
        <div className="form-group mb-3">
          <label htmlFor="email">Email</label>
          <input
            type="email"
            className="form-control"
            id="email"
            placeholder="Enter email"
            value={emailInput}
            onChange={(e) => setEmailInput(e.target.value)}
          />
        </div>
        <div className="form-group mb-3">
          <label htmlFor="phone">Phone Number</label>
          <input
            type="number"
            className="form-control"
            id="phone"
            placeholder="Enter phone"
            value={phoneInput}
            maxLength={10}
            onChange={(e) => setPhoneInput(e.target.value)}
          />
        </div>

        <div className="form-group mb-3">
          <label htmlFor="category">Category</label>
          <select
            className="form-control"
            id="category"
            onChange={(e) => {
              setCategoryInput(e.target.value);
            }}
          >
            <option value="">Choose</option>
            <option value="general">General</option>
            <option value="sc/st">SC/ST</option>
            <option value="obc">OBC</option>
          </select>
        </div>
        <div className="form-group mb-3">
          <label>Technology</label>
          <div className="form-check">
            <input
              className="form-check-input"
              type="checkbox"
              value="c"
              id="c"
              name="technology"
              onChange={technologyInputHandler}
            />
            <label className="form-check-label" htmlFor="c">
              C
            </label>
          </div>
          <div className="form-check">
            <input
              className="form-check-input"
              type="checkbox"
              value="c++"
              id="c++"
              name="technology"
              onChange={technologyInputHandler}
            />
            <label className="form-check-label" htmlFor="c++">
              C++
            </label>
          </div>
          <div className="form-check">
            <input
              className="form-check-input"
              type="checkbox"
              value="java"
              id="java"
              name="technology"
              onChange={technologyInputHandler}
            />
            <label className="form-check-label" htmlFor="java">
              Java
            </label>
          </div>
          <div className="form-check">
            <input
              className="form-check-input"
              type="checkbox"
              value="python"
              id="python"
              name="technology"
              onChange={technologyInputHandler}
            />
            <label className="form-check-label" htmlFor="python">
              Python
            </label>
          </div>
          <div className="form-check">
            <input
              className="form-check-input"
              type="checkbox"
              value="javascript"
              id="javascript"
              name="technology"
              onChange={technologyInputHandler}
            />
            <label className="form-check-label" htmlFor="javascript">
              Javascript
            </label>
          </div>
        </div>
        <button type="submit" className="btn btn-primary">
          Preview
        </button>
      </form>
    </>
  );
};

export default CreateUser;

// angular_assignment_2/src/app/components/create-user/create-user.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormControl, Validators, FormArray } from '@angular/forms';
import { Router } from '@angular/router';
import { UserRecordService } from 'src/app/services/user-record.service';

@Component({
  selector: 'app-create-user',
  templateUrl: './create-user.component.html',
  styleUrls: ['./create-user.component.css'],
})
export class CreateUserComponent implements OnInit {
  showModal: boolean = false;
  userForm = new FormGroup({
    name: new FormControl('', [
      Validators.required,
      Validators.minLength(2),
      Validators.maxLength(30),
      Validators.pattern('[a-zA-Z ]*'),
    ]),
    gender: new FormControl('', Validators.required),
    email: new FormControl('', [Validators.required, Validators.email]),
    phone: new FormControl('', [
      Validators.required,
      Validators.pattern('^[0-9]{10}$'),
    ]),
    category: new FormControl('', Validators.required),
    technology: new FormControl(''),
  });

  constructor(
    private userRecordService: UserRecordService,
    private router: Router
  ) {}

  ngOnInit(): void {}

  onSubmit() {
    if (this.userForm.valid) {
      this.showModal = !this.showModal;
    } else {
      alert('Please fill all the details.');
    }
  }

  closeModal() {
    this.showModal = !this.showModal;
  }

  addRecord() {
    this.closeModal();
    const userRecord = {
      name: this.userForm.value.name,
      gender: this.userForm.value.gender,
      email: this.userForm.value.email,
      phone: this.userForm.value.phone,
      category: this.userForm.value.category,
      technology: [],
    };
    this.userRecordService.addUserRecord(userRecord);
    this.router.navigateByUrl('/users/view');
  }
}

<app-view-user-modal
  *ngIf="showModal"
  [userDetails]="userForm.value"
  (onCancel)="closeModal()"
  (onSubmit)="addRecord()"
></app-view-user-modal>
<form [formGroup]="userForm" (ngSubmit)="onSubmit()">
  <h1 class="text-center">Enter Details</h1>
  <div class="form-group mb-3">
    <label for="name">Name</label>
    <input
      type="text"
      class="form-control"
      id="name"
      placeholder="Enter name"
      formControlName="name"
    />
    <div *ngIf="userForm.get('name')?.invalid && userForm.get('name')?.touched">
      <p class="error-text" *ngIf="userForm.get('name')?.errors?.['required']">
        Name is required.
      </p>
      <p class="error-text" *ngIf="userForm.get('name')?.errors?.['minlength']">
        Name must be at least 2 characters long.
      </p>
      <p class="error-text" *ngIf="userForm.get('name')?.errors?.['maxlength']">
        Name max length is 30.
      </p>
      <p class="error-text" *ngIf="userForm.get('name')?.errors?.['pattern']">
        Name cannot contain symbols or numbers.
      </p>
    </div>
  </div>
  <div class="form-group mb-3">
    <label>Gender</label>
    <div class="form-check form-check-inline">
      <input
        class="form-check-input"
        type="radio"
        name="gender"
        id="male"
        value="male"
        formControlName="gender"
      />
      <label class="form-check-label" for="male"> Male </label>
    </div>
    <div class="form-check form-check-inline">
      <input
        class="form-check-input"
        type="radio"
        name="gender"
        id="female"
        value="female"
        formControlName="gender"
      />
      <label class="form-check-label" for="female"> Female </label>
    </div>
    <div
      *ngIf="userForm.get('gender')?.invalid && userForm.get('gender')?.touched"
    >
      <p
        class="error-text"
        *ngIf="userForm.get('gender')?.errors?.['required']"
      >
        Gender is required.
      </p>
    </div>
  </div>
  <div class="form-group mb-3">
    <label for="email">Email</label>
    <input
      type="email"
      class="form-control"
      id="email"
      placeholder="Enter email"
      formControlName="email"
    />
    <div
      *ngIf="userForm.get('email')?.invalid && userForm.get('email')?.touched"
    >
      <p class="error-text" *ngIf="userForm.get('email')?.errors?.['required']">
        Email is required.
      </p>
      <p class="error-text" *ngIf="userForm.get('email')?.errors?.['email']">
        Invalid email address,
      </p>
    </div>
  </div>
  <div class="form-group mb-3">
    <label for="phone">Phone Number</label>
    <input
      type="tel"
      class="form-control"
      id="phone"
      placeholder="Enter phone"
      formControlName="phone"
    />
    <div
      *ngIf="userForm.get('phone')?.invalid && userForm.get('phone')?.touched"
    >
      <p class="error-text" *ngIf="userForm.get('phone')?.errors?.['required']">
        Phone no is required.
      </p>
      <p class="error-text" *ngIf="userForm.get('phone')?.errors?.['pattern']">
        Phone no should be of 10 digit. Only numbers allowed.
      </p>
    </div>
  </div>

  <div class="form-group mb-3">
    <label for="category">Category</label>
    <select class="form-control" id="category" formControlName="category">
      <option value="">Choose</option>
      <option value="general">General</option>
      <option value="sc/st">SC/ST</option>
      <option value="obc">OBC</option>
    </select>
    <div
      *ngIf="
        userForm.get('category')?.invalid && userForm.get('category')?.touched
      "
    >
      <p
        class="error-text"
        *ngIf="userForm.get('category')?.errors?.['required']"
      >
        Category is required.
      </p>
    </div>
  </div>
  <div class="form-group mb-3">
    <label>Technology</label>
    <div class="form-check">
      <input
        class="form-check-input"
        type="checkbox"
        value="c"
        id="c"
        formControlName="technology"
      />
      <label class="form-check-label" for="c"> C </label>
    </div>
    <div class="form-check">
      <input
        class="form-check-input"
        type="checkbox"
        value="c++"
        id="c++"
        formControlName="technology"
      />
      <label class="form-check-label" for="c++"> C++ </label>
    </div>
    <div class="form-check">
      <input
        class="form-check-input"
        type="checkbox"
        value="java"
        id="java"
        formControlName="technology"
      />
      <label class="form-check-label" for="java"> Java </label>
    </div>
    <div class="form-check">
      <input
        class="form-check-input"
        type="checkbox"
        value="python"
        id="python"
        formControlName="technology"
      />
      <label class="form-check-label" for="python"> Python </label>
    </div>
    <div class="form-check">
      <input
        class="form-check-input"
        type="checkbox"
        value="javascript"
        id="javascript"
        formControlName="technology"
      />
      <label class="form-check-label" for="javascript"> Javascript </label>
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Preview</button>
</form>
