// react_assignment_2/src/components/ViewUserModal.js
import React from "react";
import { useNavigate } from "react-router-dom";

const ViewUserModal = ({ handleCancel, userDetails, handleSubmit }) => {
  const navigate = useNavigate();

  const submitHandler = () => {
    handleSubmit(userDetails);

    //Hide the modal
    handleCancel();

    // redirect to view users
    navigate("/users/view");
  };
  return (
    <>
      <div className="backdrop"></div>
      <div className="modal" style={{ display: "block" }}>
        <div className="modal-dialog">
          <div className="modal-content">
            <div className="modal-header">
              <h1 className="modal-title fs-5">Verify Details</h1>
              <button
                type="button"
                className="btn-close"
                onClick={handleCancel}
              ></button>
            </div>
            <div className="modal-body">
              <ul>
                <li>
                  <b>Name:</b>
                  {userDetails.name}
                </li>
                <li>
                  <b>gender:</b>
                  {userDetails.gender}
                </li>
                <li>
                  <b>phone:</b>
                  {userDetails.phone}
                </li>
                <li>
                  <b>email:</b>
                  {userDetails.email}
                </li>
                <li>
                  <b>category:</b>
                  {userDetails.category}
                </li>
                <li>
                  <b>technology:</b>
                  {userDetails.technology.join(",")}
                </li>
              </ul>
            </div>
            <div className="modal-footer">
              <button
                type="button"
                className="btn btn-secondary"
                onClick={handleCancel}
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={submitHandler}
                className="btn btn-primary"
              >
                Submit
              </button>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default ViewUserModal;

// angular_assignment_2/src/app/components/view-user-modal/view-user-modal.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { UserRecord } from 'src/app/records';

@Component({
  selector: 'app-view-user-modal',
  templateUrl: './view-user-modal.component.html',
  styleUrls: ['./view-user-modal.component.css']
})
export class ViewUserModalComponent implements OnInit {

  @Input() userDetails!:any;
  @Output() onCancel = new EventEmitter();
  @Output() onSubmit = new EventEmitter();
  
  constructor() { }

  ngOnInit(): void {
  }

  handleCancel(){
    this.onCancel.emit();
  }

  handleSubmit(){
    this.onSubmit.emit();
  }

}

<div class="backdrop"></div>
<div class="modal" style="display: block">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5">Verify Details</h1>
        <button type="button" class="btn-close" (click)="handleCancel()"></button>
      </div>
      <div class="modal-body">
        <ul>
          <li>
            <b>Name:</b>
            {{ userDetails.name }}
          </li>
          <li>
            <b>Gender:</b>
            {{ userDetails.gender }}
          </li>
          <li>
            <b>Phone:</b>
            {{ userDetails.phone }}
          </li>
          <li>
            <b>Email:</b>
            {{ userDetails.email }}
          </li>
          <li>
            <b>Category:</b>
            {{ userDetails.category }}
          </li>
          <li>
            <b>Technology:</b>
            {{ userDetails.technology.join(",") }}
          </li>
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" (click)="handleCancel()">Cancel</button>
        <button type="button" class="btn btn-primary" (click)="handleSubmit()">Submit</button>
      </div>
    </div>
  </div>
</div>
